// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: pkg/discover/pb/discover.proto

package discoverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverFeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DiscoverFeedRequest) Reset() {
	*x = DiscoverFeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_discover_pb_discover_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverFeedRequest) ProtoMessage() {}

func (x *DiscoverFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discover_pb_discover_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverFeedRequest.ProtoReflect.Descriptor instead.
func (*DiscoverFeedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_discover_pb_discover_proto_rawDescGZIP(), []int{0}
}

type DiscoverFeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*DiscoverFeedItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *DiscoverFeedResponse) Reset() {
	*x = DiscoverFeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_discover_pb_discover_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverFeedResponse) ProtoMessage() {}

func (x *DiscoverFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discover_pb_discover_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverFeedResponse.ProtoReflect.Descriptor instead.
func (*DiscoverFeedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_discover_pb_discover_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverFeedResponse) GetItems() []*DiscoverFeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DiscoverFeedWithTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *DiscoverFeedWithTagsRequest) Reset() {
	*x = DiscoverFeedWithTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_discover_pb_discover_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverFeedWithTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverFeedWithTagsRequest) ProtoMessage() {}

func (x *DiscoverFeedWithTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discover_pb_discover_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverFeedWithTagsRequest.ProtoReflect.Descriptor instead.
func (*DiscoverFeedWithTagsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_discover_pb_discover_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverFeedWithTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DiscoverFeedItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId     string   `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	OwnerId     string   `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title       string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url         string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Tags        []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt   string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *DiscoverFeedItem) Reset() {
	*x = DiscoverFeedItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_discover_pb_discover_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverFeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverFeedItem) ProtoMessage() {}

func (x *DiscoverFeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discover_pb_discover_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverFeedItem.ProtoReflect.Descriptor instead.
func (*DiscoverFeedItem) Descriptor() ([]byte, []int) {
	return file_pkg_discover_pb_discover_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoverFeedItem) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *DiscoverFeedItem) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DiscoverFeedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DiscoverFeedItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DiscoverFeedItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DiscoverFeedItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DiscoverFeedItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_pkg_discover_pb_discover_proto protoreflect.FileDescriptor

var file_pkg_discover_pb_discover_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x62, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x48, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x31, 0x0a, 0x1b, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x57, 0x69, 0x74, 0x68, 0x54,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0xc5,
	0x01, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xc3, 0x01, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x14, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x57, 0x69, 0x74, 0x68, 0x54,
	0x61, 0x67, 0x73, 0x12, 0x25, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x57, 0x69, 0x74, 0x68, 0x54,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x2d, 0x74, 0x6f, 0x6b, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_discover_pb_discover_proto_rawDescOnce sync.Once
	file_pkg_discover_pb_discover_proto_rawDescData = file_pkg_discover_pb_discover_proto_rawDesc
)

func file_pkg_discover_pb_discover_proto_rawDescGZIP() []byte {
	file_pkg_discover_pb_discover_proto_rawDescOnce.Do(func() {
		file_pkg_discover_pb_discover_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_discover_pb_discover_proto_rawDescData)
	})
	return file_pkg_discover_pb_discover_proto_rawDescData
}

var file_pkg_discover_pb_discover_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_discover_pb_discover_proto_goTypes = []interface{}{
	(*DiscoverFeedRequest)(nil),         // 0: discover.DiscoverFeedRequest
	(*DiscoverFeedResponse)(nil),        // 1: discover.DiscoverFeedResponse
	(*DiscoverFeedWithTagsRequest)(nil), // 2: discover.DiscoverFeedWithTagsRequest
	(*DiscoverFeedItem)(nil),            // 3: discover.DiscoverFeedItem
}
var file_pkg_discover_pb_discover_proto_depIdxs = []int32{
	3, // 0: discover.DiscoverFeedResponse.items:type_name -> discover.DiscoverFeedItem
	0, // 1: discover.DiscoverService.DiscoverFeed:input_type -> discover.DiscoverFeedRequest
	2, // 2: discover.DiscoverService.DiscoverFeedWithTags:input_type -> discover.DiscoverFeedWithTagsRequest
	1, // 3: discover.DiscoverService.DiscoverFeed:output_type -> discover.DiscoverFeedResponse
	1, // 4: discover.DiscoverService.DiscoverFeedWithTags:output_type -> discover.DiscoverFeedResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_discover_pb_discover_proto_init() }
func file_pkg_discover_pb_discover_proto_init() {
	if File_pkg_discover_pb_discover_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_discover_pb_discover_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverFeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_discover_pb_discover_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverFeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_discover_pb_discover_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverFeedWithTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_discover_pb_discover_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverFeedItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_discover_pb_discover_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_discover_pb_discover_proto_goTypes,
		DependencyIndexes: file_pkg_discover_pb_discover_proto_depIdxs,
		MessageInfos:      file_pkg_discover_pb_discover_proto_msgTypes,
	}.Build()
	File_pkg_discover_pb_discover_proto = out.File
	file_pkg_discover_pb_discover_proto_rawDesc = nil
	file_pkg_discover_pb_discover_proto_goTypes = nil
	file_pkg_discover_pb_discover_proto_depIdxs = nil
}
